spring.servlet.multipart.max-file-size=25MB
spring.servlet.multipart.max-request-size=25MB



# Hibernate needs to know what dialect to use before the database metadata is available.
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=update
# Database configuration (override in environment-specific property files or via CLI)
spring.datasource.url=jdbc:postgresql://localhost:5432/tavall
spring.datasource.username=novus
spring.datasource.password=d9gHyhsFad@@83#8HkWo
tavall.client.dev-login.enabled=true
